if [[ "$ZPROF" = true ]]; then
  zmodload zsh/zprof
fi

CPU=$(uname -p)
if [[ "$CPU" == "arm" ]]; then
  HOMEBREW_PATH="/opt/homebrew"
else
  HOMEBREW_PATH="/usr/local"
fi

# Path to your oh-my-zsh installation.
export ZSH=/Users/jarih/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="theme"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git gitfast git-flow heroku mix ruby rails xcode yarn)

profzsh() {
  shell=${1-$SHELL}
  ZPROF=true $shell -i -c exit
}

timezsh() {
  shell=${1-$SHELL}
  for i in $(seq 1 10); do /usr/bin/time $shell -i -c exit; done
}

# User configuration
# export PATH="/usr/bin:/bin:/usr/sbin:/sbin:$PATH"
# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

if [[ "$CPU" == "arm" ]]; then
  export EDITOR=/opt/homebrew/bin/vim
else
  export EDITOR=/usr/local/bin/vim
fi

# No automagic cleanups
export HOMEBREW_NO_INSTALL_CLEANUP=true

# export XML_CATALOG_FILES="/usr/local/etc/xml/catalog"

if [[ "$CPU" == "arm" ]]; then
  fpath=(/opt/homebrew/share/zsh/site-functions /opt/homebrew/share/zsh-completions $fpath)
else
  fpath=(/usr/local/share/zsh/site-functions /usr/local/share/zsh-completions $fpath)
fi

eval "$(rbenv init - --no-rehash)"
eval "$(nodenv init - --no-rehash)"
eval "$(exenv init - --no-rehash)"
eval "$(direnv hook $SHELL)"

# if [ $commands[rbenv] ]; then
#   rbenv() {
#     unfunction "$0"
#     eval "$(rbenv init - --no-rehash)"
#     $0 "$@"
#   }
# fi
#
# if [ $commands[nodenv] ]; then
#   nodenv() {
#     unfunction "$0"
#     eval "$(nodenv init -)"
#     $0 "$@"
#   }
# fi
#
# if [ $commands[exenv] ]; then
#   nodenv() {
#     unfunction "$0"
#     eval "$(exenv init -)"
#     $0 "$@"
#   }
# fi
#
# if [ $commands[direnv] ]; then
#   direnv() {
#     unfunction "$0"
#     eval "$(direnv hook $SHELL)"
#     $0 "$@"
#   }
# fi

# if which yarn >/dev/null; then export PATH="$PATH:`yarn global bin `"; fi

# export RUBY_CONFIGURE_OPTS="--with-openssl-dir=$(brew --prefix openssl@1.1)"
if [[ "$CPU" == "arm" ]]; then
  export RUBY_CONFIGURE_OPTS="--with-openssl-dir=/opt/homebrew/opt/openssl@1.1"
else
  export RUBY_CONFIGURE_OPTS="--with-openssl-dir=/usr/local/opt/openssl@1.1"
fi

alias be="bundle exec"
alias rdmr="rails db:migrate:redo"

alias gcd="git checkout develop"
alias gready='git branch --merged master |command grep -vE "^(\*|\s*develop\s*|\s*master\s*$)"'
alias gsweep='git branch --merged master |command grep -vE "^(\*|\s*develop\s*|\s*master\s*$)" |command xargs -n 1 git branch -d'

alias vi="vim"

source $ZSH/oh-my-zsh.sh

if [[ "$ZPROF" = true ]]; then
  zprof
fi
