brew "ack"
brew "antigen"
brew "awscli"
brew "carthage"
brew "cocoapods"
brew "ctags"
brew "direnv"
brew "elixir-build"
brew "erlang"
brew "exenv"
brew "gh"
brew "git"
brew "git-flow"
brew "git-lfs"
brew "httpie"
brew "jemalloc"
brew "llvm"
brew "memcached", restart_service: true
brew "nodenv"
brew "p7zip"
brew "postgresql", restart_service: true
brew "rbenv"
brew "rcm"
brew "redis", restart_service: true
brew "the_silver_searcher"
brew "tig"
brew "tmux"
brew "tokei"
brew "tree"
brew "v8"
brew "vim"
brew "wget"
brew "yarn"
brew "zsh"
brew "zsh-completions"
