#!/bin/sh

set -e

CPU=$(uname -p)
if [[ "$CPU" == "arm" ]]; then
  PATH="/opt/homebrew/bin:$PATH"
else
  PATH="/usr/local/bin:$PATH"
fi

dir="`git rev-parse --git-dir`"

trap 'rm -f "$dir/$$.tags"' EXIT

git ls-files | \
  ctags --tag-relative -L - -f"$dir/$$.tags" --languages=-javascript

mv "$dir/$$.tags" "$dir/tags"
